hyperliquid:
  poll_interval_ms: 3000
  inflight_timeout_ms: 5000

perp:
  binance: [ETH_USDT, ZORA_USDT, BRETT_USDT]
  hyperliquid: [ETH_USDC, ZORA_USDC, BRETT_USDC]

sample_interval_ms: 10

fair_price:
  basis_halflife_secs: 600.0
  basis_tick_ms: 100
  pairs:
    - target_exchange: hyperliquid
      target_symbol: PERP_ETH_USDC
      reference_exchange: binance
      reference_symbol: PERP_ETH_USDT
    - target_exchange: hyperliquid
      target_symbol: PERP_ZORA_USDC
      reference_exchange: binance
      reference_symbol: PERP_ZORA_USDT
    - target_exchange: hyperliquid
      target_symbol: PERP_BRETT_USDC
      reference_exchange: binance
      reference_symbol: PERP_BRETT_USDT

inventory:
  mode: hedge
  static_target:
    target: 0.0
  hedge:
    exposure_file: "/tmp/aerobot/0x313b6755EFe1A31E16aa7D375AE918384ACD737e.json"
    poll_ms: 100
    mappings:
      ETH:
        - "0x4200000000000000000000000000000000000006"
      BTC:
        - "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
      AIXBT:
        - "0x4F9Fd6Be4a90f2620860d680c0d4d5Fb53d1A825"
      ZORA:
        - "0x1111111111166b7FE7bd91427724B487980aFc69"

skew_scale_usd: 100.0
post_only: true

vol_models:
  params_dir: "../botfed-params/vol"
  bar_data_dir: "../data/binance_ohlcv/perps/1m"
  model: "har_qlike"
  warmup_days: 2

symbols:
  - symbol: PERP_ETH_USDC
    max_stale_ms: 2000
    order_notional_usd: 100.0
    max_position_usd: 100000.0
    ref_half_spread_bps: 2
    ref_min_spread_bps: 1.5
    ref_requote_tolerance_bps: 5.0
    max_skew_bps: 1.5
    min_edge_bps: -1.0
    ref_vol: 0.35
    vol_mult_floor: 0.3
    vol_mult_cap: 5.0
    vol_symbol: "ETH"
    quote_interval_ms: 150
    warmup_secs: 10
    max_feed_age_ms: 10000
    stray_order_age_ms: 6000
  # - symbol: PERP_ZORA_USDC
  #   max_stale_ms: 2000
  #   order_notional_usd: 100.0
  #   max_position_usd: 10000.0
  #   ref_half_spread_bps: 12
  #   ref_min_spread_bps: 6
  #   ref_requote_tolerance_bps: 10.0
  #   max_skew_bps: 10.0
  #   min_edge_bps: 3.5
  #   ref_vol: 1.00
  #   vol_mult_floor: 0.3
  #   vol_mult_cap: 5.0
  #   vol_symbol: "ZORA"
  #   quote_interval_ms: 150
  #   post_only: false
  #   warmup_secs: 10
  #   max_feed_age_ms: 10000
  #   stray_order_age_ms: 6000
  #   factor_model:
  #     enabled: true
  #     factors:
  #       - symbol: PERP_ETH_USDT
  #         exchanges: [binance]
  #         beta: 0.97
  # - symbol: PERP_BRETT_USDC
  #   max_stale_ms: 2000
  #   order_notional_usd: 100.0
  #   max_position_usd: 10000.0
  #   ref_half_spread_bps: 12
  #   ref_min_spread_bps: 6
  #   ref_requote_tolerance_bps: 10.0
  #   max_skew_bps: 10.0
  #   min_edge_bps: 3.5
  #   ref_vol: 1.00
  #   vol_mult_floor: 0.3
  #   vol_mult_cap: 5.0
  #   vol_symbol: "BRETT"
  #   quote_interval_ms: 150
  #   post_only: false
  #   warmup_secs: 10
  #   max_feed_age_ms: 10000
  #   stray_order_age_ms: 6000
  #   factor_model:
  #     enabled: true
  #     factors:
  #       - symbol: PERP_ETH_USDT
  #         exchanges: [binance]
  #         beta: 1.0
